import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {Toaster} from "@/components/ui/toaster";
import ReduxProvider from "@/components/ReduxProvider";
import {QueryClient, QueryClientProvider} from "@tanstack/react-query";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    const queryClient = new QueryClient();

    return (
        <html lang="en">
        <body className={inter.className}>
        {/*<QueryClientProvider client={queryClient}>*/}
        <ReduxProvider>
            <Navbar/>
            {children}
            <Toaster/>
        </ReduxProvider>
        {/*</QueryClientProvider>*/}
        </body>
        </html>
    );
}
